authentication/urls.py
from django.urls import path, include
from .views import LoginFormView, UserRegisterView, LogoutView, link_logout

app_name = 'auth'

urlpatterns = [
     path('login/', LoginFormView.as_view(), name='login'),
     # path('register/', UserRegisterView.as_view(), name='register'),
     # path('logout/', LogoutView.as_view(), name='logout'),
     path('logout/', link_logout, name='logout'),


]

caja/urls.py
from django.urls import path
from . import views

app_name = 'cajas'

urlpatterns = [
    path('caja/', views.CajaListView.as_view(), name='caja_list'),
    path('salidas/', views.SalidaListView.as_view(), name='salida_list'),
    path('<int:pk>/', views.CajaDetailView.as_view(), name='caja_detail'),
    path('create/', views.CajaCreateView.as_view(), name='caja_create'),
    path('edit/<int:pk>/', views.CajaUpdateView.as_view(), name='salida_edit'),
    path('delete/<int:pk>', views.CajaDeleteView.as_view(), name='caja_delete'),


]

db_backup/urls.py
from django.urls import path
from . import views

app_name = 'backup'

urlpatterns = [
    path('', views.DatabaseBackupView.as_view(), name='db_backup'),
    path('export/', views.export_database, name='export_database'),
    path('import/', views.import_database, name='import_database'),
]

private/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('calendario/', views.calendarView.as_view(), name='calendar'),

]

publiprint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("private.urls")),
    path('', include("authentication.urls")),
    path('pedidos/', include("orders.urls")),
    path('clientes/', include("clientes.urls")),
    path('empleados/', include("empleados.urls")),
    path('backup/', include ("db_backup.urls")),
    path('caja/', include("caja.urls")),
    path('api-auth/', include('rest_framework.urls')),

]

clientes/models.py
# clientes/models.py
from django.db import models
from django.core.exceptions import ValidationError

def validate_eight_digits(value):
    if len(str(value)) != 8:
        raise ValidationError('El valor debe tener exactamente 8 dígitos.')

class Client(models.Model):
    name = models.CharField(max_length=60)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    phone = models.IntegerField(
        validators=[validate_eight_digits],
        blank=True, null=True
    )

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.name

private/models.py
from django.db import models

# Create your models here.

private/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, UpdateView
from clientes.models import Client
from datetime import date, timedelta
from empleados.models import Payment
from orders.models import Order
from .graphs import lastTwelveMonths, lastTwelveMonthsName
import json
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Q
import calendar

# Create your views here.
class home(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('auth:login')
    template_name = 'utilidades/inicio.html'

    def get_context_data(self, **kwargs):
        Current_date = date.today()
        Current_month = Current_date.month
        Current_year = Current_date.year
        context = super().get_context_data(**kwargs)
        all_clients = Client.objects.count()
        all_orders = Order.objects.count()

        orders_this_month = Order.objects.filter(Q(request_date__month=Current_month)).count()
        clients_this_month = Client.objects.filter(Q(created__month=Current_month)).count()

        orders_this_day = Order.objects.filter(Q(request_date=Current_date))
        delivery_now = Order.objects.filter(deadline=Current_date)        # Datos para los gráficos
        delivery_tomorrow = Order.objects.filter(deadline=Current_date+timedelta(days=1))

        clients_data = lastTwelveMonths(Client, "clientes", Current_date)
        orders_data = lastTwelveMonths(Order, "orders", Current_date)
        months_name = lastTwelveMonthsName(Current_date)

        context['current_date'] = Current_date
        context['allcients'] = all_clients
        context['allorders'] = all_orders
        context['ordersthismonth'] = orders_this_month
        context['clienthismonth'] = clients_this_month
        context['orders_this_day'] = orders_this_day
        context['delivery_now'] = delivery_now
        context['delivery_tomorrow'] = delivery_tomorrow
        context['clients_data'] = json.dumps(clients_data)
        context['orders_data'] = json.dumps(orders_data)
        context['months_name'] = json.dumps(months_name)
        return context

class calendarView(LoginRequiredMixin, TemplateView):
    template_name = 'utilidades/calendar.html'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        orders = Order.objects.all()

        # Crear eventos para órdenes
        events = [
            {
            'title': order.client.name,
            'start': order.deadline.strftime('%Y-%m-%d'),
            'end': order.deadline.strftime('%Y-%m-%d'),
            'url': reverse('verOrden', kwargs={'pk': order.id}),
            'color': 'green' if order.entregado else 'red',
            } for order in orders
        ]

        # Obtener el mes y año actual
        today = date.today()
        year = today.year
        month = today.month

        # Obtener todos los pagos
        payments = Payment.objects.filter(Q(employee__is_working=True))
        # payments = Payment.objects.all()
        # Crear eventos para pagos
        payment_events = []
        for payment in payments:
            # Validar que el día sea válido en el mes actual
            if 1 <= payment.date <= calendar.monthrange(year, month)[1]:
                payment_events.append({
                    'title': f'• {payment.employee.name}',
                    'start': f'{year}-{month:02d}-{payment.date:02d}',
                    'end': f'{year}-{month:02d}-{payment.date:02d}',
                    'color': 'blue',  # Color distintivo para pagos
                })

    # Combinar los eventos de órdenes y pagos
        events.extend(payment_events)

        context = {
        'events': json.dumps(events)
        }
        return context

private/templates/frame/nav.html
{% load static %}
<nav class="navegador">
    
    <ul>
        <li><a href="/"><img src="{% static 'img/PPlogo.svg' %}" alt="logo publiprint" class="nwlogo"></a></li>
        <li>
            <a href="{% url 'home' %}">
                <i class="bi bi-speedometer2"></i>
                Inicio
            </a>
        </li>

        <li>
            <a href="{% url 'orden' %}">
                <i class="bi bi-file-earmark-plus"></i>
                Crear Pedido
            </a>
        </li>
        <li>
            <a href="{% url 'proforma' %}">
                <i class="bi bi-files"></i>
                Pedidos
            </a>
        </li>
        <!-- <li><a href="{% url 'cajas:salida_list' %}">Salidas</a></li> -->
        <!-- <li><a href="{% url 'cajas:caja_list' %}">Caja</a></li> -->
        <li>
            <a href="{% url 'client_list' %}">
                <i class="bi bi-person-badge"></i>
                Clientes
            </a>
        </li>
        <li>
            <a href="{% url 'list_employee' %}">
                <i class="bi bi-person-workspace"></i>
                Empleados
            </a>
        </li>
        <li>
            <a href="{% url 'calendar' %}">
                <i class="bi bi-calendar-event"></i>
                Calendario
            </a>
        </li>
        <br>
        <li>
            <a href="{% url 'backup:db_backup' %}">
                <i class="bi bi-database"></i>
                Respaldo
            </a>
        </li>
        <li>
            <a href="{% url 'auth:logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                Cerrar Sesion
            </a>
        </li>

    </ul>
</nav>