caja/urls.py
from django.urls import path
from . import views

app_name = 'cajas'

urlpatterns = [
    path('caja/', views.CajaListView.as_view(), name='caja_list'),
    path('salidas/', views.SalidaListView.as_view(), name='salida_list'),
    path('<int:pk>/', views.CajaDetailView.as_view(), name='caja_detail'),
    path('create/', views.CajaCreateView.as_view(), name='caja_create'),
    path('edit/<int:pk>/', views.CajaUpdateView.as_view(), name='salida_edit'),
    path('delete/<int:pk>', views.CajaDeleteView.as_view(), name='caja_delete'),


]

db_backup/urls.py
from django.urls import path
from . import views

app_name = 'backup'

urlpatterns = [
    path('', views.DatabaseBackupView.as_view(), name='db_backup'),
    path('export/', views.export_database, name='export_database'),
    path('import/', views.import_database, name='import_database'),
]

publiprint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("private.urls")),
    path('', include("authentication.urls")),
    path('pedidos/', include("orders.urls")),
    path('clientes/', include("clientes.urls")),
    path('empleados/', include("empleados.urls")),
    path('backup/', include ("db_backup.urls")),
    path('caja/', include("caja.urls")),
    path('api-auth/', include('rest_framework.urls')),

]

db_backup/models.py
from django.db import models

# Create your models here.

db_backup/views.py
from django.conf import settings
from django.http import FileResponse
from pathlib import Path
from datetime import datetime
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.contrib import messages
import os
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required


class DatabaseBackupView(LoginRequiredMixin, TemplateView):
    template_name = 'db_backup/db_backup.html'

@login_required
def export_database(request):
    # Ruta del archivo de la base de datos
    database_path = Path(settings.BASE_DIR).joinpath('db.sqlite3')
    
    # Verifica si el archivo existe
    if os.path.exists(database_path):
        # Obtener la fecha y hora actual en el formato deseado
        current_time = datetime.now().strftime('%Y-%m-%d__%H-%M-%S')
        
        # Crear el nombre del archivo de backup con la fecha y hora
        backup_filename = f"backup_{current_time}.sqlite"
        
        # Crear la respuesta con el archivo de backup
        response = FileResponse(open(database_path, 'rb'))
        
        # Establecer el encabezado para la descarga, incluyendo el nombre del archivo con la fecha
        response['Content-Disposition'] = f'attachment; filename="{backup_filename}"'
        
        # Retornar la respuesta de descarga
        return response
    
    # Si la base de datos no existe, usar messages.error para mostrar un error
    messages.error(request, 'Archivo de base de datos no encontrado.')
    
    # Redirigir a la vista de backups
    return redirect('backup:db_backup') 

@login_required
def import_database(request):
    if request.method == 'POST' and request.FILES['file']:
        uploaded_file = request.FILES['file']
        file_path = Path(settings.BASE_DIR).joinpath('db.sqlite3')

        # Guarda el archivo subido como la nueva base de datos
        with open(file_path, 'wb') as f:
            for chunk in uploaded_file.chunks():
                f.write(chunk)

        # Mensaje de éxito usando messages.success
        messages.success(request, 'Base de datos importada correctamente.')

        # Redirige a una vista donde el mensaje se pueda mostrar
        return redirect('backup:db_backup')  # Cambia 'home' por la URL de tu página de inicio o vista correspondiente

    # Si no se pudo importar la base de datos, mostrar un mensaje de error
    messages.error(request, 'Error al importar la base de datos.')
    
    # Redirige a la misma página o a una página de error
    return redirect('backup:db_backup') 

db_backup/templates/db_backup/db_backup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <style>
        /* Contenedor principal */

/* Título */
.title {
    font-size: 28px;
    font-weight: bold;
    margin-bottom: 20px;
}

/* Diseño en grid */
.backup-grid {
    display: grid;
    grid-template-columns: 1fr auto 1fr;
    gap: 20px;
    align-items: center;
    justify-content: center;
}

/* Tarjetas */
.backup-card {
    background: #f5f5f5;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
    text-align: center;
}

/* Texto */
h3 {
    font-weight: 500;
    margin-bottom: 15px;
}

.info-text {
    color: #666;
    font-size: 14px;
}

/* Separador */
.separator {
    font-size: 20px;
    font-weight: bold;
    color: #666;
}

/* Input de archivo */
.file-input {
    display: block;
    width: 100%;
    margin-bottom: 15px;
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

/* Botón */
.btn {
    display: block;
    width: 100%;
    padding: 10px;
    background-color: #007bff;
    color: white;
    text-decoration: none;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 16px;
    transition: background 0.3s ease;
}

.btn:hover {
    background-color: #0056b3;
}

/* Responsivo */
@media (max-width: 600px) {
    .backup-grid {
        grid-template-columns: 1fr;
    }
}

    </style>
    <h1 class="title">Respaldo</h1>

    <div class="backup-grid">
        <div class="backup-card">
            <h3>Importar Base de Datos</h3>
            <form action="{% url 'backup:import_database' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input class="file-input" type="file" name="file" accept=".sqlite" required>
                <button class="btn" type="submit">Cargar Datos</button>
            </form>
        </div>

        <p class="separator">o</p>

        <div class="backup-card">
            <h3>Exportar Base de Datos</h3>
            <p class="info-text">Guarda el archivo en un lugar seguro</p>
            <a class="btn" href="{% url 'backup:export_database' %}">Descargar Datos</a>
        </div>
    </div>
</div>
{% endblock %}