caja/urls.py
from django.urls import path
from . import views

app_name = 'cajas'

urlpatterns = [
    path('caja/', views.CajaListView.as_view(), name='caja_list'),
    path('salidas/', views.SalidaListView.as_view(), name='salida_list'),
    path('<int:pk>/', views.CajaDetailView.as_view(), name='caja_detail'),
    path('create/', views.CajaCreateView.as_view(), name='caja_create'),
    path('edit/<int:pk>/', views.CajaUpdateView.as_view(), name='salida_edit'),
    path('delete/<int:pk>', views.CajaDeleteView.as_view(), name='caja_delete'),


]

clientes/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.ClientListView.as_view(), name='client_list'),
    path('crear/', views.ClientCreatedView.as_view(), name='client_create'),
    path('<int:pk>/', views.clientDetailView.as_view(), name = 'client_detail'),
    path('actualizar/<int:pk>/', views.ClientUpdateView.as_view(), name='client_update'),
    path('eliminar/<int:pk>/', views.ClientDeleteView.as_view(), name='client_delete'),

    
    path('client-suggestions/', views.ClientSuggestionsView.as_view(), name='client-suggestions'),
]

empleados/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.EmployeeListView.as_view(), name='list_employee'),
    path('crear/', views.EmployeeCreateView.as_view(), name='create_employee'),
    path('<int:pk>/', views.EmployeeDetailView.as_view(), name='detail_employee'),
    path('actualizar/<int:pk>/', views.EmployeeUpdateView.as_view(), name='update_employee'),
    path('eliminar/<int:pk>/', views.EmployeeDeleteView.as_view(), name='delete_employee'),
]

publiprint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("private.urls")),
    path('', include("authentication.urls")),
    path('pedidos/', include("orders.urls")),
    path('clientes/', include("clientes.urls")),
    path('empleados/', include("empleados.urls")),
    path('backup/', include ("db_backup.urls")),
    path('caja/', include("caja.urls")),
    path('api-auth/', include('rest_framework.urls')),

]

clientes/models.py
# clientes/models.py
from django.db import models
from django.core.exceptions import ValidationError

def validate_eight_digits(value):
    if len(str(value)) != 8:
        raise ValidationError('El valor debe tener exactamente 8 dígitos.')

class Client(models.Model):
    name = models.CharField(max_length=60)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    phone = models.IntegerField(
        validators=[validate_eight_digits],
        blank=True, null=True
    )

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.name

empleados/models.py
from django.db import models
from django.core.exceptions import ValidationError

def validate_eight_digits(value):
    if len(str(value)) != 8:
        raise ValidationError('El valor debe tener exactamente 8 dígitos.')

# class PaymentDate(models.Model):
#     employee = models.ForeignKey('Employee', related_name='payment_dates_related', on_delete=models.CASCADE)
#     payment_date = models.DateField(blank=True, null=True)

#     def __str__(self):
#         return f"Pago de {self.employee.name} - {self.payment_date}"

class Employee(models.Model):
    POSITION_CHOICES = [
        ('atencion', 'Atención al Cliente'),
        ('costura', 'Costura y Confección'),
        ('impresion', 'Impresión'),
        ('sublimacion', 'Sublimación'),
    ]
    
    name = models.CharField(max_length=60)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    phone = models.IntegerField(
        validators=[validate_eight_digits],
        blank=True, null=True
    )
    is_working = models.BooleanField(default=True)
    position = models.CharField(max_length=20, choices=POSITION_CHOICES, default='atencion')
    # payment_dates = models.ManyToManyField(PaymentDate, related_name='employees_related', blank=True)

    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"

    def __str__(self):
        return self.name

class Payment(models.Model):
    date = models.IntegerField()
    mount = models.IntegerField(blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

clientes/views.py
from django.shortcuts import render
from .models import Client
from django.views.generic import ListView, CreateView, DeleteView, View, DetailView, UpdateView
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from orders.models import Order
from django.http import JsonResponse
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class clientDetailView(LoginRequiredMixin, DetailView):
    template_name = 'cliente/viewClient.html'
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client = self.get_object()  # Obtener la instancia del cliente actual
        context['pedidos'] = Order.objects.filter(Q(client__id__iexact=client.id))
        return context
    
class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'cliente/listClient.html'
    context_object_name = 'clientes'
    paginate_by = 10 
    def get_queryset(self):
        query = self.request.GET.get('query_clientes')
        if query:
            return Client.objects.filter(Q(name__icontains=query)).order_by('id')
        else:
            return Client.objects.all().order_by('-created')

class ClientCreatedView(LoginRequiredMixin, CreateView):
    model = Client
    template_name = 'cliente/createClient.html'
    success_url = reverse_lazy('client_list')
    fields = ['name', 'phone']
    def handle_no_permission(self):
        return HttpResponseRedirect(reverse_lazy('client_list'))
    

class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    template_name = 'cliente/updateClient.html'
    fields = ['name', 'phone']

    def form_valid(self, form):
        # messages.success(self.request, "Cliente actualizado con éxito.")
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('client_detail', kwargs={'pk': self.object.id})

class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = 'cliente/deleteClient.html'
    success_url = reverse_lazy('client_list')

    def delete(self, request, *args, **kwargs):
        # messages.success(self.request, "Cliente eliminado con éxito.")
        return super().delete(request, *args, **kwargs)

###############################################
    
class ClientSuggestionsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            term = request.GET.get('term', '')
            clientes = Client.objects.filter(Q(name__icontains=term) | Q(phone__icontains=term))
            results = [{'id': cliente.id, 'name': cliente.name, 'phone': cliente.phone} for cliente in clientes]
            return JsonResponse(results, safe=False)
        return JsonResponse([], safe=False)
    

empleados/views.py
from django.shortcuts import render
from orders.models import Employee
from django.views.generic import ListView, CreateView, DeleteView, View, DetailView, UpdateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
#############################################


class EmployeeListView(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'empleado/listEmployee.html'
    context_object_name = 'empleados'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('query_empleados')
        if query:
            return Employee.objects.filter(name__icontains=query).order_by('id')
        return Employee.objects.all().order_by('id')

class EmployeeCreateView(LoginRequiredMixin, CreateView):
    model = Employee
    template_name = 'empleado/createEmployee.html'
    fields = ['name', 'phone']
    success_url = reverse_lazy('list_employee')

class EmployeeDetailView(LoginRequiredMixin, DetailView):
    model = Employee
    template_name = 'empleado/detailEmployee.html'
    context_object_name = 'empleado'

class EmployeeUpdateView(LoginRequiredMixin, UpdateView):
    model = Employee
    template_name = 'empleado/updateEmployee.html'
    fields = ['name', 'phone', 'is_working']
    success_url = reverse_lazy('list_employee')

class EmployeeDeleteView(LoginRequiredMixin, DeleteView):
    model = Employee
    template_name = 'empleado/deleteEmployee.html'
    success_url = reverse_lazy('list_employee')

clientes/templates/empleado/createEmployee.html
{% extends "base.html" %}
{% block title%}
<title>Crear empleado</title>
{% endblock %}

{% block content%}
<h1>Crear Empleado</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
<a href="{% url 'list_employee' %}">Volver a la lista</a>
{% endblock %}

clientes/templates/empleado/deleteEmployee.html
{% extends "base.html" %}
{% block title%}
<title>Eliminar empleado</title>
{% endblock %}

{% block content%}
<h1>Eliminar Empleado</h1>
<p>¿Estás seguro de que deseas eliminar al empleado "{{ object.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
</form>
<a href="{% url 'list_employee' %}">Cancelar</a>


{% endblock %}

clientes/templates/empleado/detailEmployee.html
{% extends "base.html" %}
{% block title%}
<title>Detalle empleado</title>
{% endblock %}

{% block content%}
<h1>Detalles del Empleado</h1>
<p><strong>Nombre:</strong> {{ empleado.name }}</p>
<p><strong>Teléfono:</strong> {{ empleado.phone }}</p>
<p><strong>Activo:</strong> {{ empleado.is_working }}</p>
<a class="button secondary" href="{% url 'list_employee' %}">Volver a la lista</a>
<a class="button" href="{% url 'update_employee' empleado.id %}">Editar</a>
<a class="button red" href="{% url 'delete_employee' empleado.id %}">Eliminar</a>

{% endblock %}

clientes/templates/empleado/listEmployee.html
{% extends "base.html" %}
{% load static %}
{% block title%}
<title>Listado de Empleados</title>
{% endblock %}

{% block content%}

<h1 class="title">Listado de Empleados</h1>

<div class="flex-container">
  <div class="">
    <form method="get" action="{% url 'list_employee' %}">
      <input type="text" class="input-hiden" name="query_empleados" value="{{ query }}" placeholder="Buscar por nombre...">
      <button class="button green" type="submit">Buscar <i class="bi bi-search"></i></button>
    </form>
  </div>

  <div class="" style="margin-left: auto;">
    <a href="{% url 'create_employee' %}" class="button green">
      Agregar Empleado
      <i class="bi bi-person-add"></i>
    </a>
  </div>
</div>
  
  <table class="table table_list">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Nombre</th>
        <th scope="col">Puesto</th>
        <th scope="col">Telefono</th>
        <th scope="col" >Estado</th>
      </tr>
    </thead>
    <tbody>
      {% for empleado in empleados %}
      <tr>
        <td scope="row">{{empleado.id}}</td>
        
          <td>  <a href="{% url 'detail_employee' empleado.id %}">{{ empleado.name }}</a></td>
          <td scope="col">{{empleado.get_position_display }}</td>
          <td><a href="https://wa.me/502{{empleado.phone}}?text=Buen%20dia.%20Le%20saludamos%20de%20PubliPrint" target="_blank">{{empleado.phone}}</a></td>
          <td>
            {% if empleado.is_working %}
            <a class="button green">Activo <span class="bi bi-check "></span> </a>
            {% else %}
            <a class="button red">Inactivo <span class="bi bi-x"></span></a>
            {% endif %}
          </td>

      </tr>

      {% endfor %}
    </tbody>
  </table>
  <div class="pagination">
    <div class="step-links">
        {% if page_obj.has_previous %}
            <a class="page_link" href="?page=1">&laquo; Primera</a>
            <a class="page_link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
            {% else %}
            <a class="page_link_disabled" aria-disabled="true">&laquo; Primera</a>
            <a class="page_link_disabled" aria-disabled="true">Anterior</a>
        {% endif %}

        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a class="page_link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
            <a class="page_link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
            {% else %}
            <a class="page_link_disabled" aria-disabled="true">Siguiente</a>
            <a class="page_link_disabled" aria-disabled="true">Última &raquo;</a>
        {% endif %}
    </div>
</div>
{% endblock %}

clientes/templates/empleado/updateEmployee.html
{% extends "base.html" %}
{% block title%}
<title>Actualizar empleado</title>
{% endblock %}

{% block content%}
<h1>Editar Empleado</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Actualizar</button>
</form>
<a href="{% url 'list_employee' %}">Volver a la lista</a>

{% endblock %}