caja/urls.py
from django.urls import path
from . import views

app_name = 'cajas'

urlpatterns = [
    path('caja/', views.CajaListView.as_view(), name='caja_list'),
    path('salidas/', views.SalidaListView.as_view(), name='salida_list'),
    path('<int:pk>/', views.CajaDetailView.as_view(), name='caja_detail'),
    path('create/', views.CajaCreateView.as_view(), name='caja_create'),
    path('edit/<int:pk>/', views.CajaUpdateView.as_view(), name='salida_edit'),
    path('delete/<int:pk>', views.CajaDeleteView.as_view(), name='caja_delete'),


]

publiprint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("private.urls")),
    path('', include("authentication.urls")),
    path('pedidos/', include("orders.urls")),
    path('clientes/', include("clientes.urls")),
    path('empleados/', include("empleados.urls")),
    path('backup/', include ("db_backup.urls")),
    path('caja/', include("caja.urls")),
    path('api-auth/', include('rest_framework.urls')),

]

caja/models.py
from django.db import models

class TipoCaja(models.Model):
    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre
    
# Create your models here.

class Salida(models.Model):
    caja = models.ForeignKey(TipoCaja,on_delete=models.CASCADE, default=2)
    description = models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    total = models.FloatField()
    def __str__(self):
        return self.description
    

caja/views.py
from django.utils import timezone

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from caja.models import Salida
from orders.models import Order
from django.db.models import Q


def get_combined_list():
    entradas = Order.objects.all()
    salidas = Salida.objects.all()
    
    # Combinar ambas consultas en una lista
    lista_combinada = list(entradas) + list(salidas)
    
    # Ordenar la lista combinada por fecha
    lista_ordenada = sorted(lista_combinada, key=lambda obj: obj.created)
    
    return lista_ordenada

def totales(lista_ord):
    totals = {}  # Diccionario para almacenar los totales
    
    for movimiento in lista_ord:
        if movimiento.caja.id == 1:
            if 'total_entrada' not in totals:
                totals['total_entrada'] = 0
            totals['total_entrada'] += movimiento.totalentrada()
        else:
            if 'total_salida' not in totals:
                totals['total_salida'] = 0
            totals['total_salida'] += movimiento.total 
            
    return totals

class CajaListView(ListView):
    model = Salida
    context_object_name = 'salidas'
    template_name = 'caja/list.html'

    def get_queryset(self):
        query = self.request.GET.get('caja_date')

        lista_combinada = get_combined_list()
        if query:
            year, month = query.split("-")
            year, month = int(year), int(month)
   
            return [item for item in lista_combinada if item.created.year == year and item.created.month == month]
        else:
            year, month = timezone.now().year, timezone.now().month
            return [item for item in lista_combinada if item.created.year == year and item.created.month == month]
                      
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lista_combinada = self.get_queryset()
        
        
        # Obtener los totales
        totals = totales(lista_combinada)
        alltotals = totals.get('total_entrada', 0) - totals.get('total_salida', 0)

        context['alltotals'] = alltotals
        context['total'] = totals
        context['movimientos'] = lista_combinada
        return context

class SalidaListView(ListView):
    model = Salida
    context_object_name = 'salidas'
    paginate_by = 10
    template_name = 'salida/list.html'
    order_by = '-created'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by(self.order_by)

class CajaDetailView(DetailView):
    model = Salida
    template_name = 'caja/detail.html'

class CajaCreateView(CreateView):
    model = Salida
    template_name = 'salida/form.html' 
    fields = ['description', 'total']
    success_url = reverse_lazy('cajas:salida_list')

class CajaUpdateView(UpdateView):
    model = Salida
    template_name = 'salida/editar.html' 
    fields = ['description', 'total']
    success_url = reverse_lazy('cajas:salida_list')

class CajaDeleteView(DeleteView):
    model = Salida
    template_name = 'caja/confirm_delete.html'
    success_url = reverse_lazy('cajas:salida_list')

caja/templates/salida/confirm_delete.html
{% extends 'dashboard.html' %}
{% block title %} Confirmacion {% endblock %}
{% block content %}
        <h1>¿Estás seguro de que deseas eliminar la Plaga?</h1>
        
        <p>Por favor, confirma si deseas eliminar la siguiente plaga:</p>
        <p><strong>Nombre:</strong> {{ object.name }}</p>
        <p><strong>Descripción:</strong> {{ object.description }}</p>
        
        <form method="post">
            {% csrf_token %}
            <button type="submit">Sí, eliminar</button>
            <a href="{% url 'plagues:plague_detail' object.pk %}">Cancelar</a>
        </form>
    </body>

    {% endblock %}

caja/templates/salida/editar.html
{% extends 'base.html' %}

{% block title %}<title>Editar salida</title>{% endblock %}

{% block content %}
  <h2>Salida</h2>
  <form method="post">
    {% csrf_token %}
    <div>
      {% for field in form %}
        <div class="form_row">
          {{ field.label_tag }}
          {{ field }}
          {% if field.errors %}
            <div class="errors">
              {% for error in field.errors %}
                <span class="error">{{ error }}</span>
              {% endfor %}
            </div>
          {% endif %}
        </div>
      {% endfor %}
    </div>
    <a href="{% url 'cajas:salida_list' %}" class="button red">Cancelar</a>
    <button type="submit" class="button green">Guardar</button>
  </form>
{% endblock %}

caja/templates/salida/form.html
{% extends 'base.html' %}
{% block title %} <title>Salida</title> {% endblock %}
{% block content %}
    <h1>{% block heading %}{% endblock %}</h1>

    <div class="form_edit_container">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Guardar</button>
        </form>
        <a href="{% url 'cajas:caja_list'%}">Cancelar</a>
    </div>
        
    {% endblock %}

caja/templates/salida/list.html
{% extends 'base.html' %}

{% block title %} <title>Salidas</title> {% endblock %}

{% block content %}
<a href="{% url 'cajas:caja_create' %}" class="button red">Crear Salida</a>
<h1>Salidas</h1>

<table class="caja_table">
    <thead>
        <tr>
        <th>Fecha</th>
        <th>Descripcion</th>
        <th>Salen</th>
        </tr>
    </thead>
<tbody>
    {% for salida in salidas %}  
    <tr>
        <td>{{salida.created|date:"d/m/Y"}}</td>  
        <td><a href="{% url 'cajas:salida_edit' salida.id %}">{{salida.description}}</a></td>
        <td>Q{{salida.total}}</td>
    </tr>
    {% endfor %}
</tbody>

</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Primera</a>
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}